2022-02-23 17:16:26,167 INFO    MainThread:1082 [wandb_setup.py:_flush():71] setting env: {}
2022-02-23 17:16:26,167 INFO    MainThread:1082 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-23 17:16:26,167 INFO    MainThread:1082 [wandb_init.py:_log_setup():371] Logging user logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220223_171626-8kdcfb4f/logs/debug.log
2022-02-23 17:16:26,168 INFO    MainThread:1082 [wandb_init.py:_log_setup():372] Logging internal logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220223_171626-8kdcfb4f/logs/debug-internal.log
2022-02-23 17:16:26,168 INFO    MainThread:1082 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f31c2af9a50>
2022-02-23 17:16:26,168 INFO    MainThread:1082 [wandb_init.py:init():404] calling init triggers
2022-02-23 17:16:26,168 INFO    MainThread:1082 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-23 17:16:26,168 INFO    MainThread:1082 [wandb_init.py:init():460] starting backend
2022-02-23 17:16:26,169 INFO    MainThread:1082 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-23 17:16:26,214 INFO    MainThread:1082 [backend.py:ensure_launched():216] starting backend process...
2022-02-23 17:16:26,265 INFO    MainThread:1082 [backend.py:ensure_launched():222] started backend process with pid: 1134
2022-02-23 17:16:26,267 INFO    MainThread:1082 [wandb_init.py:init():469] backend started and connected
2022-02-23 17:16:26,311 INFO    MainThread:1082 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-23 17:16:26,311 INFO    MainThread:1082 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-23 17:16:26,312 INFO    MainThread:1082 [wandb_init.py:init():533] updated telemetry
2022-02-23 17:16:26,428 INFO    MainThread:1082 [wandb_init.py:init():563] communicating current version
2022-02-23 17:16:28,200 INFO    MainThread:1082 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-23 17:16:28,203 INFO    MainThread:1082 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-23 17:16:28,446 INFO    MainThread:1082 [wandb_init.py:init():606] starting run threads in backend
2022-02-23 17:16:33,464 INFO    MainThread:1082 [wandb_run.py:_console_start():1810] atexit reg
2022-02-23 17:16:33,465 INFO    MainThread:1082 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-23 17:16:33,465 INFO    MainThread:1082 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-23 17:16:33,467 INFO    MainThread:1082 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-23 17:16:33,467 INFO    MainThread:1082 [wandb_init.py:init():633] run started, returning control to user process
2022-02-23 17:16:35,270 INFO    MainThread:1082 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-23 17:16:35,271 INFO    MainThread:1082 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-23 17:17:50,306 INFO    MainThread:1082 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-23 17:17:50,326 INFO    MainThread:1082 [wandb_setup.py:_flush():71] setting env: {}
2022-02-23 17:17:50,327 INFO    MainThread:1082 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-23 17:17:50,327 INFO    MainThread:1082 [wandb_init.py:_log_setup():371] Logging user logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220223_171750-37mq8b4e/logs/debug.log
2022-02-23 17:17:50,327 INFO    MainThread:1082 [wandb_init.py:_log_setup():372] Logging internal logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220223_171750-37mq8b4e/logs/debug-internal.log
2022-02-23 17:17:50,328 INFO    MainThread:1082 [wandb_init.py:init():404] calling init triggers
2022-02-23 17:17:50,328 INFO    MainThread:1082 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-23 17:17:50,328 INFO    MainThread:1082 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 8kdcfb4f
2022-02-23 17:17:50,330 INFO    MainThread:1082 [wandb_run.py:finish():1457] finishing run simon-donike/SRCNN/8kdcfb4f
2022-02-23 17:17:50,332 INFO    MainThread:1082 [jupyter.py:save_history():429] not saving jupyter history
2022-02-23 17:17:50,332 INFO    MainThread:1082 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-23 17:17:50,332 INFO    MainThread:1082 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-23 17:17:50,332 INFO    MainThread:1082 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-23 17:17:50,334 INFO    MainThread:1082 [wandb_run.py:_restore():1752] restore
2022-02-23 17:17:50,554 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-23 17:17:50,832 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-23 17:17:51,795 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25181
}

2022-02-23 17:17:51,901 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25181
}

2022-02-23 17:17:52,007 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25181
}

2022-02-23 17:17:52,110 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-23 17:17:52,216 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-23 17:17:52,319 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-23 17:17:52,422 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-23 17:17:52,525 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-23 17:17:53,104 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}

2022-02-23 17:17:53,544 INFO    MainThread:1082 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25181
  total_bytes: 25181
}
local_info {
}

2022-02-23 17:17:55,350 INFO    MainThread:1082 [wandb_run.py:_append_files():2180] logging synced files
